### ISSUE TITLE
"Harry" is spelled as "harryl"

### ISSUE THREAD

**Issue by v0idk-dev** [formcept/whiteboard#18]
https://github.com/formcept/whiteboard/blob/7876044dd8e2f928043ff2fc800d7e30ff72a0cd/nbviewer/notebooks/data/harrypotter/Book%201%20-%20The%20Philosopher's%20Stone.txt#L14841

**Comment by anujsrc** [comment]
This is coming from open-source data. Doesn't require any change. Might be taken as a good case for spelling correction utilities and fuzzy search
